### PR TITLE
Encapsulate localstorage and allow bomb to be dropped more than once

### LINKED ISSUE #2: Override's Backbone.sync... not ideal if you are using in an Backbone app
I know you just used the Backbone.localstorage plugin, but that plugin is very destructive in that it means you must absolutely use localstorage for your datastore for all Backbone models/collections by default.

Instead, flickrbomb should set the localstorage sync method per model/collection.

### PR DESCRIPTION
**Pull request by kmiyashiro**
Now Backbone friendly.

Resolves #2

This encapsulates the localstorage stuff and only attaches it to the model/collection sync props instead of Backbone.sync.

It also changes the usage from an immediately firing function, to a singleton. Just instantiate it once and use it whenever you add more placeholders, perfect for those dynamic (Backbone) app prototypes.

### CODE REVIEW

**Comment by mkelly12** [comment]
Thanks for the patch. This looks great, my only concern about pulling this into master is that it requires you to call .bomb. I agree this is the correct approach, and necessary when working with dynamic elements, but we believe that all our open-source scripts should be as easy to use as possible for people that may not be that js savvy.

What do you think about firing the bomb method when the FlickrBomb script is loaded? This should fix the issue with dynamic content as well since you can just fire .bomb() again when you add new elements.

**Comment by kmiyashiro** [comment]
Sounds good. I can add that call, something like `if ($('[href=^flickr://]').length) callbombhere` at the end of the script file.

**Comment by kmiyashiro** [comment]
I added the immediate call on script include and edited the demo to reflect the new calls.

If you merge this, make sure to edit the readme.

**Comment by mkelly12** [comment]
Looks good! Thanks for the commit.

**Pull request merged**
